language: python
env:
  global:
  - POETRY_VERSION=0.12.17
  - ADVARCHS_ENV=build
  - ADVARCHS_DOCKER_IMAGE=elessarelfstone/advarchs
  - secure: WgWBVvm7QYSTmrRmuHErxEFJ1EhMvXO2JgzFcD7qfmI7K8ZQzQCUsI5tTCiWR90WXEjHsqT/1frR9WKTI45LkgZvqlJlS9PXkbzXAhmxgoIMzbDjtIqyWnb6MffZxM3s8DBsFzZYhfw9pQBBvqjWIac4XYGH4ONVU9aDhGWz6cdKvDQNTObdAibmPkieWia9ogE7Jb7acE2PqTADvOmW3jhqwyC481f2kbjM6yPrEcrvpQ8OaJsj1DWv2d4L1/D6j2oq2gnYjxU93rHW2a5W3cVWeeWw34gw6B1PuMTE8CjzIDsLFqwA64tc6LRMc+5AGOw/pMAa2Pp3wRawM/kbv5aZxBS8oSb23c18c5EL8MYN8BWjVbAtKs48GpJGFwA/gIS0R5DhaI4JteCTtQSdjatws9fhHrlMo7qWUvWo05tF4cA9+9uPUxVHr/JZXLt3ng3X2f1Da0QpF5xBjtF0CfV9IOBZDG2UYUluC2I4Oxt0lhSzHz18JmoIIKPvpnXyzls1L29Bn0NTdy0tZgoLOkne2pdt7cS/HG59rvuaZFYNN9y1NKygYVicVa91Le5o1+wSezN5fVPOicJ1SQGE6TyJRBC0nlIecgcnjInicpz0Qpc1F/Yp+jLGuivMriwJfuL6rZM9AxBowrdqGhUPtP9/fTxi97PwB8ZR3DlDGWk=
  - secure: Mht7/9z7g1lsHgR2VAHt09i8F7KLLNcMslnMYcRbrQlhpbyjw/16yYrzoHTFkscYNmLvbW+4VbrtyEu+/I+h8TmWGbVQy18kgIb5UcLZU+pUZoFVFMJU5HDDc8Xl/oxZOr5h4HgfzTHvQhgtAbXUte71HUtkaspwcfWzdcsJPTJCJ6N+/U2q1R+g9N8qc4eqx645Y6X4HRqN1XXrrNJ7thnRbrTCaD2UvQGzSgeB33iNPITw/QvfiRbsqXYPQR8CwyzQssmGFlErZRHxaBnp01FI2kyl3vwGP+ndXOMbWciyzZaaT8BejGYKwiZ8EKqSZXsHx65AX8xMJAMo4T8aLTIEAfK4cYPfoHFxa4Igd2eO6owJ4j9A87eOj7tlwa/v8pO5Pmfa954EgEF3zqwgqlIoNj1x4d9+xYa/yTIEVzHn9oPrXAo5ngYQ1Skw9P4u62wxvyyKd/7d0qvlfxyB+nIarrmHiJ1Si+69Ohi0U3e6Ik0iZfyK3xZ96M3PoNSz0dtDRAVQr5SmyyuKSUoyj6QDY+NVWDU0yCRqtCyScMGlhcBbjGF4NV8T4lCgsp0AvNgeMujJb78veDeb7MZyhtYxsQmiiHTqpBBQ1vScFPtID30xp8h4BKHtzx0hD1VFlPJ1MOEus5CAbuM1EQfBCx73wcK2sOcd92Qfnp+wEEM=
matrix:
  include:
  - name: Python 3.6 on Ubuntu 18.04 Bionic
    dist: bionic
    os: linux
    python: 3.6
  - name: Python 3.7 on Ubuntu 18.04 Bionic
    dist: bionic
    os: linux
    python: 3.7
  - name: Python 3.8-dev on Ubuntu 18.04 Bionic
    dist: bionic
    os: linux
    python: 3.8-dev
  - name: Python 3.7 on Alpine
    sudo: required
    services:
    - docker
    before_install:
    - docker image build --build-arg ADVARCHS_ENV=$ADVARCHS_ENV -t $ADVARCHS_DOCKER_IMAGE
      .
    install: []
    script:
    - docker run --rm $ADVARCHS_DOCKER_IMAGE
  - name: Python 3.7 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python
    - python -m pip install --upgrade pip
    - choco install 7zip
    - pip3 install -q poetry==$POETRY_VERSION
    script:
    - poetry run pytest
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
before_install:
- pip install -q poetry==$POETRY_VERSION
- sudo apt-get install p7zip-full p7zip-rar
install:
- poetry install
script:
- pytest
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  - provider: script
    script: poetry publish
    skip_cleanup: true
    on:
      tags: true
      branch:
      - /^v\d+\.\d+(\.\d+)?$/
      condition: "$TRAVIS_PYTHON_VERSION == 3.8-dev"
  - provider: script
    script: poetry publish
    skip_cleanup: true
    on:
      tags: true
      branch:
      - /^v\d+\.\d+(\.\d+)?\.[abdr]+\S*$/
      condition: "$TRAVIS_PYTHON_VERSION == 3.8-dev"
